apiVersion: v1
kind: Pod
metadata:
  name: mon-pod
  labels:
    app: mon-webapp
spec:
  containers:
    - name: mon-pod
      image: mmumshad/simple-webapp-color:latest
      ports:
        - containerPort: 80
      env:
        - name: APP_COLOR
          value: {{ .Values.pod.color }}